org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34
gradle.user.home=/home/user/.gradle
org.gradle.caching=true

# Keystore properties (added for signing)
storePassword=${KEY_STORE_PASSWORD}
keyPassword=${KEY_PASSWORD}
storeFile=android/app/keystore.jks
keyAlias=${KEY_ALIAS}